name: Build Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build . --file Dockerfile --tag ${{secrets.DH_USERNAME}}/react-get-request:latest
      - run: docker login -u ${{secrets.DH_USERNAME}} -p ${{secrets.DH_PASSWORD}}
      - run: docker push ${{secrets.DH_USERNAME}}/react-get-request:latest